// Importa la fuente JetBrains Mono desde Google Fonts usando el paquete next/font/google
import { JetBrains_Mono } from "next/font/google";
// Importa el archivo de estilos globales
import "./globals.css";

// Configura la fuente JetBrains Mono con las opciones especificadas
const jetbrainsMono = JetBrains_Mono({
  variable: '--font-jetbrainsMono', // Define una variable CSS para la fuente
  subsets: ["latin"], // Especifica los subconjuntos de caracteres a incluir
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"] // Especifica los pesos de la fuente a incluir
});

// Define los metadatos del documento HTML
export const metadata = {
  title: "Create Next App", // Título de la página
  description: "Generated by create next app", // Descripción de la página
};

// Define el componente RootLayout que envuelve toda la aplicación
export default function RootLayout({ children }) {
  return (
    <html lang="en"> {/* Define el idioma del documento */}
      <body className={jetbrainsMono.variable}> {/* Aplica la variable de la fuente al cuerpo del documento */}
        {children} {/* Renderiza los componentes hijos */}
      </body>
    </html>
  );
}